import mirror from 'mirror-to-object-pairs';

export default mirror([
  'Empty',
  'App',
  'Auth',
  'Accounts',
  'Wallet',
  'ConfirmationsTab',
  'Settings',
  'Onboarding',
  'Onboarding2',
  'QrScanner',

  'UserConfirmations',
  'SelectAccountToLogin',
  'SelectMultiAccountToLogin',
  'RecoveryWords',
  'RecoveryHavenId',
  'AreYouSure',
  'Welcome',
  'RecoverExistingAccount',
  'WelcomeOfficially',
  'CheckBackupWords',
  'Attention',
  'FirstAccount',
  'ScanQROrRecover',
  'SuccessfullyImported',
  'ImportExistingAccounts',
  'MyAccounts',
  'LoginHistory',
]);
